name: gaming

services:
  web:
    build:
      context: ..
      dockerfile: web.Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ../apps/web/.env
    environment:
      DATABASE_URL: postgresql://postgres:mypassword@postgres:5432/gaming
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - gaming-network

  postgres:
    image: postgres:17
    container_name: gaming-postgres
    environment:
      POSTGRES_DB: gaming
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - '5432:5432'
    volumes:
      - gaming_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - gaming-network

networks:
  gaming-network:
    driver: bridge

volumes:
  gaming_postgres_data:
